### ISSUE TITLE
ability to override alert theme color

### ISSUE THREAD

**Issue by mkhairi** [Daemonite/material#149]
Hi, 
Request:  add ability to choose between color, darker, lighter as variable.

```scss
@each $color, $values in $theme-colors {
  .alert-#{$color} {
    background-color: map-get(theme-color($color), darker);
    color: color-yiq(map-get(theme-color($color), lighter));
  }
}
```

btw, thanks for this awesome work.
