### ISSUE TITLE
Datepicker inside modal

### ISSUE THREAD

**Issue by Wibble199** [Daemonite/material#20]
When a datepicker is used inside a modal dialog, a graphical error occurs with the datepicker's black background:
![datepicker-error-0](https://cloud.githubusercontent.com/assets/3984322/7550132/e562261c-f64d-11e4-9513-6169c5f3f279.png)
I tried using a very crude hack which seemed to make it look okay on desktop:
```css
.modal .picker__holder {
	margin-top: 49px;
	margin-bottom: 49px;
	overflow-y: hidden;
	margin-left: 17px;
	width: calc(100% - 34px);
}
```
![image](https://cloud.githubusercontent.com/assets/3984322/7550140/371fd260-f64e-11e4-95c6-0b0ae4747d9e.png)
But it doesn't really work when it comes to mobile:
![image](https://cloud.githubusercontent.com/assets/3984322/7550141/525984ae-f64e-11e4-8bfa-e72de174dff2.png)
As you can see, it cuts off the controls at the bottom of the datepicker.

Would it be possible to maybe move the datepicker holder so that it is part of the body instead of the parent div or something similar?
