### ISSUE TITLE
how to use css variables

### ISSUE THREAD

**Issue by iocast** [Daemonite/material#229]
you wrote in the doc that css variables can be used change the colors. But in the compiled css under `daemonite-material\css\` I cannot see any color attribute is using `var(--abc)`. Can you elaborate how to use these css variables described in the doc.

many thanks
iocast

**Comment by djibe** [comment]
Css vars are declared at the beginning of daemonite and bootstrap CSS files. 

:root {
  --amber: #ffc107;
  --blue: #2196f3;
  --blue-grey: #607d8b;
}

To call a CSS var in your own CSS, write
.my-class {
  background-color: var(--amber);
}

This is basic CSS, please close issue.

**Comment by iocast** [comment]
thanks for the reply

Sadly is does not work. What i tried is to change the colors for `--primary` etc.
this is my css

```css
@import 'daemonite-material/css/material.css';
:root {
  --primary: #77c565;
  --secondary: #927628;
}
```

What I expect is that for e.g. for the css class `is-selected` the new color `#77c565` is used.
currently it uses the following css

```css
.floating-label.is-focused label {
    color: #ff4081;
}
```

or do I miss something
